import type { LoomoraConfig } from "./config-types";

/** Built-in values used when no provider or override is supplied. */
const defaultConfig: Required<LoomoraConfig> = {
  socials: {
    behance: { name: "Behance", placeholder: "ex: username" },
    discord: { name: "Discord", placeholder: "ex: username" },
    dribbble: { name: "Dribbble", placeholder: "ex: username" },
    facebook: { name: "Facebook", placeholder: "ex: username" },
    github: { name: "GitHub", placeholder: "ex: username" },
    instagram: { name: "Instagram", placeholder: "ex: username" },
    linkedin: { name: "LinkedIn", placeholder: "ex: username" },
    pinterest: { name: "Pinterest", placeholder: "ex: username" },
    snapchat: { name: "Snapchat", placeholder: "ex: username" },
    spotify: { name: "Spotify", placeholder: "ex: username" },
    telegram: { name: "Telegram", placeholder: "ex: username" },
    threads: { name: "Threads", placeholder: "ex: username" },
    tiktok: { name: "TikTok", placeholder: "ex: username" },
    wechat: { name: "WeChat", placeholder: "ex: 123456789" },
    whatsapp: { name: "WhatsApp", placeholder: "ex: 123456789" },
    x: { name: "X (Twitter)", placeholder: "ex: username" },
    youtube: { name: "YouTube", placeholder: "ex: channel name" },
  },
  countries: {
    AF: { name: "Afghanistan" },
    AL: { name: "Albania" },
    DZ: { name: "Algeria" },
    AS: { name: "American Samoa" },
    AD: { name: "Andorra" },
    AO: { name: "Angola" },
    AI: { name: "Anguilla" },
    AQ: { name: "Antarctica" },
    AR: { name: "Argentina" },
    AM: { name: "Armenia" },
    AW: { name: "Aruba" },
    AU: { name: "Australia" },
    AT: { name: "Austria" },
    AZ: { name: "Azerbaijan" },
    BS: { name: "Bahamas" },
    BH: { name: "Bahrain" },
    BD: { name: "Bangladesh" },
    BB: { name: "Barbados" },
    BY: { name: "Belarus" },
    BE: { name: "Belgium" },
    BZ: { name: "Belize" },
    BJ: { name: "Benin" },
    BM: { name: "Bermuda" },
    BT: { name: "Bhutan" },
    BO: { name: "Bolivia" },
    BA: { name: "Bosnia and Herzegovina" },
    BW: { name: "Botswana" },
    BR: { name: "Brazil" },
    IO: { name: "British Indian Ocean Territory" },
    VG: { name: "British Virgin Islands" },
    BN: { name: "Brunei Darussalam" },
    BG: { name: "Bulgaria" },
    BF: { name: "Burkina Faso" },
    BI: { name: "Burundi" },
    KH: { name: "Cambodia" },
    CM: { name: "Cameroon" },
    CA: { name: "Canada" },
    CV: { name: "Cape Verde" },
    KY: { name: "Cayman Islands" },
    CF: { name: "Central African Republic" },
    TD: { name: "Chad" },
    CL: { name: "Chile" },
    CN: { name: "China" },
    CX: { name: "Christmas Island" },
    CC: { name: "Cocos (Keeling) Islands" },
    CO: { name: "Colombia" },
    KM: { name: "Comoros" },
    CG: { name: "Congo" },
    CD: { name: "Congo (Democratic Republic)" },
    CK: { name: "Cook Islands" },
    CR: { name: "Costa Rica" },
    CI: { name: "Cote-d-Ivoire" },
    HR: { name: "Croatia" },
    CU: { name: "Cuba" },
    CW: { name: "Curaçao" },
    CY: { name: "Cyprus" },
    CZ: { name: "Czech Republic" },
    DK: { name: "Denmark" },
    DJ: { name: "Djibouti" },
    DM: { name: "Dominica" },
    DO: { name: "Dominican Republic" },
    EC: { name: "Ecuador" },
    EG: { name: "Egypt" },
    SV: { name: "El Salvador" },
    GQ: { name: "Equatorial Guinea" },
    ER: { name: "Eritrea" },
    EE: { name: "Estonia" },
    SZ: { name: "Eswatini" },
    ET: { name: "Ethiopia" },
    FK: { name: "Falkland Islands" },
    FO: { name: "Faroe Islands" },
    FJ: { name: "Fiji" },
    FI: { name: "Finland" },
    FR: { name: "France" },
    GF: { name: "French Guiana" },
    PF: { name: "French Polynesia" },
    GA: { name: "Gabon" },
    GM: { name: "Gambia" },
    GE: { name: "Georgia" },
    DE: { name: "Germany" },
    GH: { name: "Ghana" },
    GI: { name: "Gibraltar" },
    GR: { name: "Greece" },
    GL: { name: "Greenland" },
    GD: { name: "Grenada" },
    GP: { name: "Guadeloupe" },
    GU: { name: "Guam" },
    GG: { name: "Guernsey" },
    GT: { name: "Guatemala" },
    GN: { name: "Guinea" },
    GW: { name: "Guinea-Bissau" },
    GY: { name: "Guyana" },
    HT: { name: "Haiti" },
    HM: { name: "Heard Island and McDonald Islands" },
    VA: { name: "Holy See" },
    HN: { name: "Honduras" },
    HK: { name: "Hong Kong" },
    HU: { name: "Hungary" },
    IS: { name: "Iceland" },
    IM: { name: "Isle of Man" },
    IN: { name: "India" },
    ID: { name: "Indonesia" },
    IR: { name: "Iran" },
    IQ: { name: "Iraq" },
    IE: { name: "Ireland" },
    IT: { name: "Italy" },
    JM: { name: "Jamaica" },
    JP: { name: "Japan" },
    JE: { name: "Jersey" },
    JO: { name: "Jordan" },
    KZ: { name: "Kazakhstan" },
    KE: { name: "Kenya" },
    KI: { name: "Kiribati" },
    KP: { name: "North Korea" },
    KR: { name: "South Korea" },
    KW: { name: "Kuwait" },
    KG: { name: "Kyrgyzstan" },
    LA: { name: "Laos" },
    LV: { name: "Latvia" },
    LB: { name: "Lebanon" },
    LS: { name: "Lesotho" },
    LR: { name: "Liberia" },
    LY: { name: "Libya" },
    LI: { name: "Liechtenstein" },
    LT: { name: "Lithuania" },
    LU: { name: "Luxembourg" },
    MO: { name: "Macau" },
    MP: { name: "Northern Mariana Islands" },
    MK: { name: "North Macedonia" },
    MG: { name: "Madagascar" },
    MW: { name: "Malawi" },
    MY: { name: "Malaysia" },
    MV: { name: "Maldives" },
    ML: { name: "Mali" },
    MT: { name: "Malta" },
    MH: { name: "Marshall Islands" },
    MQ: { name: "Martinique" },
    MR: { name: "Mauritania" },
    MU: { name: "Mauritius" },
    YT: { name: "Mayotte" },
    MX: { name: "Mexico" },
    FM: { name: "Micronesia" },
    MD: { name: "Moldova" },
    MC: { name: "Monaco" },
    MN: { name: "Mongolia" },
    ME: { name: "Montenegro" },
    MS: { name: "Montserrat" },
    MA: { name: "Morocco" },
    MZ: { name: "Mozambique" },
    MM: { name: "Myanmar" },
    NA: { name: "Namibia" },
    NR: { name: "Nauru" },
    NP: { name: "Nepal" },
    NL: { name: "Netherlands" },
    NC: { name: "New Caledonia" },
    NZ: { name: "New Zealand" },
    NI: { name: "Nicaragua" },
    NE: { name: "Niger" },
    NG: { name: "Nigeria" },
    NU: { name: "Niue" },
    NF: { name: "Norfolk Island" },
    NO: { name: "Norway" },
    OM: { name: "Oman" },
    PK: { name: "Pakistan" },
    PW: { name: "Palau" },
    PS: { name: "Palestine" },
    PA: { name: "Panama" },
    PG: { name: "Papua New Guinea" },
    PY: { name: "Paraguay" },
    PE: { name: "Peru" },
    PH: { name: "Philippines" },
    PL: { name: "Poland" },
    PT: { name: "Portugal" },
    PR: { name: "Puerto Rico" },
    QA: { name: "Qatar" },
    RE: { name: "Réunion" },
    RO: { name: "Romania" },
    RU: { name: "Russia" },
    RW: { name: "Rwanda" },
    BL: { name: "Saint Barthélemy" },
    SH: { name: "Saint Helena" },
    KN: { name: "Saint Kitts and Nevis" },
    LC: { name: "Saint Lucia" },
    MF: { name: "Saint Martin" },
    PM: { name: "Saint Pierre and Miquelon" },
    VC: { name: "Saint Vincent and the Grenadines" },
    WS: { name: "Samoa" },
    SM: { name: "San Marino" },
    SA: { name: "Saudi Arabia" },
    SN: { name: "Senegal" },
    RS: { name: "Serbia" },
    SC: { name: "Seychelles" },
    SL: { name: "Sierra Leone" },
    SG: { name: "Singapore" },
    SX: { name: "Sint Maarten" },
    SK: { name: "Slovakia" },
    SI: { name: "Slovenia" },
    SB: { name: "Solomon Islands" },
    SO: { name: "Somalia" },
    ZA: { name: "South Africa" },
    GS: { name: "South Georgia and the South Sandwich Islands" },
    ES: { name: "Spain" },
    LK: { name: "Sri Lanka" },
    SD: { name: "Sudan" },
    SR: { name: "Suriname" },
    ST: { name: "São Tomé and Príncipe" },
    SJ: { name: "Svalbard and Jan Mayen" },
    SE: { name: "Sweden" },
    CH: { name: "Switzerland" },
    SY: { name: "Syria" },
    TW: { name: "Taiwan" },
    TJ: { name: "Tajikistan" },
    TZ: { name: "Tanzania" },
    TH: { name: "Thailand" },
    TL: { name: "Timor-Leste" },
    TG: { name: "Togo" },
    TK: { name: "Tokelau" },
    TO: { name: "Tonga" },
    TT: { name: "Trinidad and Tobago" },
    TN: { name: "Tunisia" },
    TR: { name: "Turkey" },
    TM: { name: "Turkmenistan" },
    TC: { name: "Turks and Caicos Islands" },
    TV: { name: "Tuvalu" },
    UG: { name: "Uganda" },
    UA: { name: "Ukraine" },
    AE: { name: "United Arab Emirates" },
    GB: { name: "United Kingdom" },
    US: { name: "United States" },
    UY: { name: "Uruguay" },
    UZ: { name: "Uzbekistan" },
    VU: { name: "Vanuatu" },
    VE: { name: "Venezuela" },
    VN: { name: "Vietnam" },
    WF: { name: "Wallis and Futuna" },
    EH: { name: "Western Sahara" },
    YE: { name: "Yemen" },
    ZM: { name: "Zambia" },
    ZW: { name: "Zimbabwe" },
  },
};

export { defaultConfig };
