import type { LoomoraConfig } from './config-types'

/** Built-in values used when no provider or override is supplied. */
const defaultConfig: Required<LoomoraConfig> = {
  // Translations
  hasTranslationStrategy: false,
  translations: {
    socials: {
      behance: { name: 'Behance', placeholder: 'ex: username' },
      discord: { name: 'Discord', placeholder: 'ex: username' },
      dribbble: { name: 'Dribbble', placeholder: 'ex: username' },
      facebook: { name: 'Facebook', placeholder: 'ex: username' },
      github: { name: 'GitHub', placeholder: 'ex: username' },
      instagram: { name: 'Instagram', placeholder: 'ex: username' },
      linkedin: { name: 'LinkedIn', placeholder: 'ex: username' },
      pinterest: { name: 'Pinterest', placeholder: 'ex: username' },
      snapchat: { name: 'Snapchat', placeholder: 'ex: username' },
      spotify: { name: 'Spotify', placeholder: 'ex: username' },
      telegram: { name: 'Telegram', placeholder: 'ex: username' },
      threads: { name: 'Threads', placeholder: 'ex: username' },
      tiktok: { name: 'TikTok', placeholder: 'ex: username' },
      wechat: { name: 'WeChat', placeholder: 'ex: 123456789' },
      whatsapp: { name: 'WhatsApp', placeholder: 'ex: 123456789' },
      x: { name: 'X (Twitter)', placeholder: 'ex: username' },
      youtube: { name: 'YouTube', placeholder: 'ex: channel name' },
    },
    countries: {
      AF: { name: 'Afghanistan' },
      AL: { name: 'Albania' },
      DZ: { name: 'Algeria' },
      AS: { name: 'American Samoa' },
      AD: { name: 'Andorra' },
      AO: { name: 'Angola' },
      AI: { name: 'Anguilla' },
      AQ: { name: 'Antarctica' },
      AR: { name: 'Argentina' },
      AM: { name: 'Armenia' },
      AW: { name: 'Aruba' },
      AU: { name: 'Australia' },
      AT: { name: 'Austria' },
      AZ: { name: 'Azerbaijan' },
      BS: { name: 'Bahamas' },
      BH: { name: 'Bahrain' },
      BD: { name: 'Bangladesh' },
      BB: { name: 'Barbados' },
      BY: { name: 'Belarus' },
      BE: { name: 'Belgium' },
      BZ: { name: 'Belize' },
      BJ: { name: 'Benin' },
      BM: { name: 'Bermuda' },
      BT: { name: 'Bhutan' },
      BO: { name: 'Bolivia' },
      BA: { name: 'Bosnia and Herzegovina' },
      BW: { name: 'Botswana' },
      BR: { name: 'Brazil' },
      IO: { name: 'British Indian Ocean Territory' },
      VG: { name: 'British Virgin Islands' },
      BN: { name: 'Brunei Darussalam' },
      BG: { name: 'Bulgaria' },
      BF: { name: 'Burkina Faso' },
      BI: { name: 'Burundi' },
      KH: { name: 'Cambodia' },
      CM: { name: 'Cameroon' },
      CA: { name: 'Canada' },
      CV: { name: 'Cape Verde' },
      KY: { name: 'Cayman Islands' },
      CF: { name: 'Central African Republic' },
      TD: { name: 'Chad' },
      CL: { name: 'Chile' },
      CN: { name: 'China' },
      CX: { name: 'Christmas Island' },
      CC: { name: 'Cocos (Keeling) Islands' },
      CO: { name: 'Colombia' },
      KM: { name: 'Comoros' },
      CG: { name: 'Congo' },
      CD: { name: 'Congo (Democratic Republic)' },
      CK: { name: 'Cook Islands' },
      CR: { name: 'Costa Rica' },
      CI: { name: 'Cote-d-Ivoire' },
      HR: { name: 'Croatia' },
      CU: { name: 'Cuba' },
      CW: { name: 'Curaçao' },
      CY: { name: 'Cyprus' },
      CZ: { name: 'Czech Republic' },
      DK: { name: 'Denmark' },
      DJ: { name: 'Djibouti' },
      DM: { name: 'Dominica' },
      DO: { name: 'Dominican Republic' },
      EC: { name: 'Ecuador' },
      EG: { name: 'Egypt' },
      SV: { name: 'El Salvador' },
      GQ: { name: 'Equatorial Guinea' },
      ER: { name: 'Eritrea' },
      EE: { name: 'Estonia' },
      SZ: { name: 'Eswatini' },
      ET: { name: 'Ethiopia' },
      FK: { name: 'Falkland Islands' },
      FO: { name: 'Faroe Islands' },
      FJ: { name: 'Fiji' },
      FI: { name: 'Finland' },
      FR: { name: 'France' },
      GF: { name: 'French Guiana' },
      PF: { name: 'French Polynesia' },
      GA: { name: 'Gabon' },
      GM: { name: 'Gambia' },
      GE: { name: 'Georgia' },
      DE: { name: 'Germany' },
      GH: { name: 'Ghana' },
      GI: { name: 'Gibraltar' },
      GR: { name: 'Greece' },
      GL: { name: 'Greenland' },
      GD: { name: 'Grenada' },
      GP: { name: 'Guadeloupe' },
      GU: { name: 'Guam' },
      GG: { name: 'Guernsey' },
      GT: { name: 'Guatemala' },
      GN: { name: 'Guinea' },
      GW: { name: 'Guinea-Bissau' },
      GY: { name: 'Guyana' },
      HT: { name: 'Haiti' },
      HM: { name: 'Heard Island and McDonald Islands' },
      VA: { name: 'Holy See' },
      HN: { name: 'Honduras' },
      HK: { name: 'Hong Kong' },
      HU: { name: 'Hungary' },
      IS: { name: 'Iceland' },
      IM: { name: 'Isle of Man' },
      IN: { name: 'India' },
      ID: { name: 'Indonesia' },
      IR: { name: 'Iran' },
      IQ: { name: 'Iraq' },
      IE: { name: 'Ireland' },
      IT: { name: 'Italy' },
      JM: { name: 'Jamaica' },
      JP: { name: 'Japan' },
      JE: { name: 'Jersey' },
      JO: { name: 'Jordan' },
      KZ: { name: 'Kazakhstan' },
      KE: { name: 'Kenya' },
      KI: { name: 'Kiribati' },
      KP: { name: 'North Korea' },
      KR: { name: 'South Korea' },
      KW: { name: 'Kuwait' },
      KG: { name: 'Kyrgyzstan' },
      LA: { name: 'Laos' },
      LV: { name: 'Latvia' },
      LB: { name: 'Lebanon' },
      LS: { name: 'Lesotho' },
      LR: { name: 'Liberia' },
      LY: { name: 'Libya' },
      LI: { name: 'Liechtenstein' },
      LT: { name: 'Lithuania' },
      LU: { name: 'Luxembourg' },
      MO: { name: 'Macau' },
      MP: { name: 'Northern Mariana Islands' },
      MK: { name: 'North Macedonia' },
      MG: { name: 'Madagascar' },
      MW: { name: 'Malawi' },
      MY: { name: 'Malaysia' },
      MV: { name: 'Maldives' },
      ML: { name: 'Mali' },
      MT: { name: 'Malta' },
      MH: { name: 'Marshall Islands' },
      MQ: { name: 'Martinique' },
      MR: { name: 'Mauritania' },
      MU: { name: 'Mauritius' },
      YT: { name: 'Mayotte' },
      MX: { name: 'Mexico' },
      FM: { name: 'Micronesia' },
      MD: { name: 'Moldova' },
      MC: { name: 'Monaco' },
      MN: { name: 'Mongolia' },
      ME: { name: 'Montenegro' },
      MS: { name: 'Montserrat' },
      MA: { name: 'Morocco' },
      MZ: { name: 'Mozambique' },
      MM: { name: 'Myanmar' },
      NA: { name: 'Namibia' },
      NR: { name: 'Nauru' },
      NP: { name: 'Nepal' },
      NL: { name: 'Netherlands' },
      NC: { name: 'New Caledonia' },
      NZ: { name: 'New Zealand' },
      NI: { name: 'Nicaragua' },
      NE: { name: 'Niger' },
      NG: { name: 'Nigeria' },
      NU: { name: 'Niue' },
      NF: { name: 'Norfolk Island' },
      NO: { name: 'Norway' },
      OM: { name: 'Oman' },
      PK: { name: 'Pakistan' },
      PW: { name: 'Palau' },
      PS: { name: 'Palestine' },
      PA: { name: 'Panama' },
      PG: { name: 'Papua New Guinea' },
      PY: { name: 'Paraguay' },
      PE: { name: 'Peru' },
      PH: { name: 'Philippines' },
      PL: { name: 'Poland' },
      PT: { name: 'Portugal' },
      PR: { name: 'Puerto Rico' },
      QA: { name: 'Qatar' },
      RE: { name: 'Réunion' },
      RO: { name: 'Romania' },
      RU: { name: 'Russia' },
      RW: { name: 'Rwanda' },
      BL: { name: 'Saint Barthélemy' },
      SH: { name: 'Saint Helena' },
      KN: { name: 'Saint Kitts and Nevis' },
      LC: { name: 'Saint Lucia' },
      MF: { name: 'Saint Martin' },
      PM: { name: 'Saint Pierre and Miquelon' },
      VC: { name: 'Saint Vincent and the Grenadines' },
      WS: { name: 'Samoa' },
      SM: { name: 'San Marino' },
      SA: { name: 'Saudi Arabia' },
      SN: { name: 'Senegal' },
      RS: { name: 'Serbia' },
      SC: { name: 'Seychelles' },
      SL: { name: 'Sierra Leone' },
      SG: { name: 'Singapore' },
      SX: { name: 'Sint Maarten' },
      SK: { name: 'Slovakia' },
      SI: { name: 'Slovenia' },
      SB: { name: 'Solomon Islands' },
      SO: { name: 'Somalia' },
      ZA: { name: 'South Africa' },
      GS: { name: 'South Georgia and the South Sandwich Islands' },
      ES: { name: 'Spain' },
      LK: { name: 'Sri Lanka' },
      SD: { name: 'Sudan' },
      SR: { name: 'Suriname' },
      ST: { name: 'São Tomé and Príncipe' },
      SJ: { name: 'Svalbard and Jan Mayen' },
      SE: { name: 'Sweden' },
      CH: { name: 'Switzerland' },
      SY: { name: 'Syria' },
      TW: { name: 'Taiwan' },
      TJ: { name: 'Tajikistan' },
      TZ: { name: 'Tanzania' },
      TH: { name: 'Thailand' },
      TL: { name: 'Timor-Leste' },
      TG: { name: 'Togo' },
      TK: { name: 'Tokelau' },
      TO: { name: 'Tonga' },
      TT: { name: 'Trinidad and Tobago' },
      TN: { name: 'Tunisia' },
      TR: { name: 'Turkey' },
      TM: { name: 'Turkmenistan' },
      TC: { name: 'Turks and Caicos Islands' },
      TV: { name: 'Tuvalu' },
      UG: { name: 'Uganda' },
      UA: { name: 'Ukraine' },
      AE: { name: 'United Arab Emirates' },
      GB: { name: 'United Kingdom' },
      US: { name: 'United States' },
      UY: { name: 'Uruguay' },
      UZ: { name: 'Uzbekistan' },
      VU: { name: 'Vanuatu' },
      VE: { name: 'Venezuela' },
      VN: { name: 'Vietnam' },
      WF: { name: 'Wallis and Futuna' },
      EH: { name: 'Western Sahara' },
      YE: { name: 'Yemen' },
      ZM: { name: 'Zambia' },
      ZW: { name: 'Zimbabwe' },
    },
    timezones: {
      // Africa
      'africa/cairo': { name: 'Cairo', region: 'Africa' },
      'africa/casablanca': { name: 'Casablanca', region: 'Africa' },
      'africa/johannesburg': { name: 'Johannesburg', region: 'Africa' },
      'africa/lagos': { name: 'Lagos', region: 'Africa' },
      'africa/nairobi': { name: 'Nairobi', region: 'Africa' },
      // America
      'america/new_york': { name: 'New York', region: 'America' },
      'america/chicago': { name: 'Chicago', region: 'America' },
      'america/denver': { name: 'Denver', region: 'America' },
      'america/los_angeles': { name: 'Los Angeles', region: 'America' },
      'america/anchorage': { name: 'Anchorage', region: 'America' },
      'america/honolulu': { name: 'Honolulu', region: 'America' },
      'america/sao_paulo': { name: 'Sao Paulo', region: 'America' },
      'america/argentina/buenos_aires': { name: 'Buenos Aires', region: 'America' },
      'america/mexico_city': { name: 'Mexico City', region: 'America' },
      'america/toronto': { name: 'Toronto', region: 'America' },
      'america/caracas': { name: 'Caracas', region: 'America' },
      'america/st_johns': { name: "St. John's", region: 'America' },
      // Asia
      'asia/singapore': { name: 'Singapore', region: 'Asia' },
      'asia/kuala_lumpur': { name: 'Kuala Lumpur', region: 'Asia' },
      'asia/bangkok': { name: 'Bangkok', region: 'Asia' },
      'asia/jakarta': { name: 'Jakarta', region: 'Asia' },
      'asia/manila': { name: 'Manila', region: 'Asia' },
      'asia/hong_kong': { name: 'Hong Kong', region: 'Asia' },
      'asia/shanghai': { name: 'Shanghai', region: 'Asia' },
      'asia/tokyo': { name: 'Tokyo', region: 'Asia' },
      'asia/seoul': { name: 'Seoul', region: 'Asia' },
      'asia/pyongyang': { name: 'Pyongyang', region: 'Asia' },
      'asia/kolkata': { name: 'Kolkata', region: 'Asia' },
      'asia/dhaka': { name: 'Dhaka', region: 'Asia' },
      'asia/karachi': { name: 'Karachi', region: 'Asia' },
      'asia/kabul': { name: 'Kabul', region: 'Asia' },
      'asia/dubai': { name: 'Dubai', region: 'Asia' },
      'asia/tehran': { name: 'Tehran', region: 'Asia' },
      'asia/riyadh': { name: 'Riyadh', region: 'Asia' },
      'asia/damascus': { name: 'Damascus', region: 'Asia' },
      'asia/kathmandu': { name: 'Kathmandu', region: 'Asia' },
      'asia/yangon': { name: 'Yangon', region: 'Asia' },
      'asia/almaty': { name: 'Almaty', region: 'Asia' },
      'asia/tashkent': { name: 'Tashkent', region: 'Asia' },
      'asia/baku': { name: 'Baku', region: 'Asia' },
      'asia/yerevan': { name: 'Yerevan', region: 'Asia' },
      'asia/tbilisi': { name: 'Tbilisi', region: 'Asia' },
      // Australia
      'australia/sydney': { name: 'Sydney', region: 'Australia' },
      'australia/melbourne': { name: 'Melbourne', region: 'Australia' },
      'australia/brisbane': { name: 'Brisbane', region: 'Australia' },
      'australia/perth': { name: 'Perth', region: 'Australia' },
      'australia/adelaide': { name: 'Adelaide', region: 'Australia' },
      'australia/darwin': { name: 'Darwin', region: 'Australia' },
      'australia/eucla': { name: 'Eucla', region: 'Australia' },
      'australia/lord_howe': { name: 'Lord Howe', region: 'Australia' },
      // Europe
      'europe/london': { name: 'London', region: 'Europe' },
      'europe/paris': { name: 'Paris', region: 'Europe' },
      'europe/berlin': { name: 'Berlin', region: 'Europe' },
      'europe/rome': { name: 'Rome', region: 'Europe' },
      'europe/madrid': { name: 'Madrid', region: 'Europe' },
      'europe/amsterdam': { name: 'Amsterdam', region: 'Europe' },
      'europe/brussels': { name: 'Brussels', region: 'Europe' },
      'europe/zurich': { name: 'Zurich', region: 'Europe' },
      'europe/vienna': { name: 'Vienna', region: 'Europe' },
      'europe/prague': { name: 'Prague', region: 'Europe' },
      'europe/warsaw': { name: 'Warsaw', region: 'Europe' },
      'europe/stockholm': { name: 'Stockholm', region: 'Europe' },
      'europe/oslo': { name: 'Oslo', region: 'Europe' },
      'europe/helsinki': { name: 'Helsinki', region: 'Europe' },
      'europe/athens': { name: 'Athens', region: 'Europe' },
      'europe/bucharest': { name: 'Bucharest', region: 'Europe' },
      'europe/istanbul': { name: 'Istanbul', region: 'Europe' },
      'europe/moscow': { name: 'Moscow', region: 'Europe' },
      'europe/kiev': { name: 'Kiev', region: 'Europe' },
      'europe/minsk': { name: 'Minsk', region: 'Europe' },
      'europe/dublin': { name: 'Dublin', region: 'Europe' },
      'europe/lisbon': { name: 'Lisbon', region: 'Europe' },
      'europe/reykjavik': { name: 'Reykjavik', region: 'Europe' },
      // Pacific
      'pacific/auckland': { name: 'Auckland', region: 'Pacific' },
      'pacific/fiji': { name: 'Fiji', region: 'Pacific' },
      'pacific/tahiti': { name: 'Tahiti', region: 'Pacific' },
      'pacific/marquesas': { name: 'Marquesas', region: 'Pacific' },
      'pacific/gambier': { name: 'Gambier', region: 'Pacific' },
      'pacific/easter': { name: 'Easter', region: 'Pacific' },
      'pacific/galapagos': { name: 'Galapagos', region: 'Pacific' },
      'pacific/guadalcanal': { name: 'Guadalcanal', region: 'Pacific' },
      'pacific/noumea': { name: 'Noumea', region: 'Pacific' },
      'pacific/port_moresby': { name: 'Port Moresby', region: 'Pacific' },
      'pacific/guam': { name: 'Guam', region: 'Pacific' },
      'pacific/saipan': { name: 'Saipan', region: 'Pacific' },
      'pacific/palau': { name: 'Palau', region: 'Pacific' },
      'pacific/chatham': { name: 'Chatham', region: 'Pacific' },
      'pacific/kiritimati': { name: 'Kiritimati', region: 'Pacific' },
      'pacific/apia': { name: 'Apia', region: 'Pacific' },
      'pacific/tongatapu': { name: 'Tongatapu', region: 'Pacific' },
      // Atlantic
      'atlantic/azores': { name: 'Azores', region: 'Atlantic' },
      'atlantic/cape_verde': { name: 'Cape Verde', region: 'Atlantic' },
      'atlantic/canary': { name: 'Canary', region: 'Atlantic' },
      'atlantic/reykjavik': { name: 'Reykjavik', region: 'Atlantic' },
      'atlantic/south_georgia': { name: 'South Georgia', region: 'Atlantic' },
      // Indian
      'indian/maldives': { name: 'Maldives', region: 'Indian' },
      'indian/mauritius': { name: 'Mauritius', region: 'Indian' },
      'indian/reunion': { name: 'Reunion', region: 'Indian' },
      'indian/seychelles': { name: 'Seychelles', region: 'Indian' },
      'indian/comoro': { name: 'Comoro', region: 'Indian' },
      'indian/madagascar': { name: 'Madagascar', region: 'Indian' },
      'indian/mayotte': { name: 'Mayotte', region: 'Indian' },
      'indian/cocos': { name: 'Cocos', region: 'Indian' },
      'indian/christmas': { name: 'Christmas', region: 'Indian' },
    },
    useDates: {
      locales: {},
      months: {
        JAN: { name: 'January', shortName: 'Jan' },
        FEB: { name: 'February', shortName: 'Feb' },
        MAR: { name: 'March', shortName: 'Mar' },
        APR: { name: 'April', shortName: 'Apr' },
        MAY: { name: 'May', shortName: 'May' },
        JUN: { name: 'June', shortName: 'Jun' },
        JUL: { name: 'July', shortName: 'Jul' },
        AUG: { name: 'August', shortName: 'Aug' },
        SEP: { name: 'September', shortName: 'Sep' },
        OCT: { name: 'October', shortName: 'Oct' },
        NOV: { name: 'November', shortName: 'Nov' },
        DEC: { name: 'December', shortName: 'Dec' },
      },
    },
    form: { dialogTitle: 'Form', dialogCloseTitle: 'Close' },
    textEditor: { menusView: 'View', menusEdit: 'Edit', menusFormat: 'Format', menusInsert: 'Insert' },
    searchField: { clearSearchTitle: 'Clear', searchButtonTitle: 'Search' },
    password: {
      placeholder: 'e.g.: ********',
      confirmMatch: 'Match',
      confirmMismatch: 'Mismatch',
      copyTooltip: 'Copy {password} to clipboard',
      get generate() {
        return `Generate ${defaultConfig?.form?.password?.length}bit {password}`
      },
      hideTooltip: 'Hide {password}',
      label: '{password}',
      missing: 'Please enter a password.',
      missingButton: 'Enter a password',
      showTooltip: 'Show {password}',
      validation: {
        weak: 'Weak',
        medium: 'Medium',
        strong: 'Strong',
        minLength: {
          get short() {
            return `${defaultConfig?.form?.password?.length}+ letter(s) long`
          },
          get long() {
            return `At least ${defaultConfig?.form?.password?.maxLength}+ letter(s) long`
          },
        },
        lowercase: {
          get short() {
            return `${defaultConfig?.form?.password?.lowercaseLength}+ Lowercase letter(s) long`
          },
          get long() {
            return `At least ${defaultConfig?.form?.password?.lowercaseLength}+ Lowercase letter(s) long`
          },
        },
        uppercase: {
          get short() {
            return `${defaultConfig?.form?.password?.uppercaseLength}+ Uppercase letter(s) long`
          },
          get long() {
            return `At least ${defaultConfig?.form?.password?.uppercaseLength}+ Uppercase letter(s) long`
          },
        },
        number: {
          get short() {
            return `${defaultConfig?.form?.password?.numbersLength}+ Number(s) long`
          },
          get long() {
            return `At least ${defaultConfig?.form?.password?.numbersLength}+ Number(s) long`
          },
        },
        special: {
          get short() {
            return `${defaultConfig?.form?.password?.specialCharsLength}+ special character(s) long`
          },
          get long() {
            return `At least ${defaultConfig?.form?.password?.specialCharsLength}+ special character(s) long`
          },
        },
      },
    },
    phone: {
      startPlaceholder: '[{start}]XXXXXXXXX',
      startPlaceholderOne: '{start}XXXXXXXXX',
      defaultTitle: 'Country',
      startError: 'Phone number must start with one of [{start}] for {country}',
    },
    autoComplete: {
      loadingState: 'Loading options...',
      emptyState: 'No options available',
      searchPlaceholder: 'Search...',
      selectedCount: '{count} selected',
    },
    uploader: {
      allCatAccepted: 'All {cat} file(s) allowed',
      extsAccepted: 'Only {exts} files allowed',
      duplicateFileRule: 'File/Files already uploaded',
      maxFilesRule: 'Max of {max} file(s) allowed',
      maxFilesSizeRule: 'Max total size of {max} allowed',
      maxSizeRule: 'Max size of {max} allowed',
      minFilesRule: 'Min of {min} file(s) required',
      minFilesSizeRule: 'Min total size of {min} required',
      minSizeRule: 'Min size of {min} required',
      uploadError: 'Failed to upload, Please try again',
      acceptRule: 'Only {rules} files allowed',
      dialogTitle: 'Manage Uploaded file(s)',
      dropFilesHere: { title: 'Drop Files Here', description: 'Drop your file(s) here to upload' },
      actions: { removeFile: 'Remove file', update: 'Update file', view: 'View file' },
      item: { id: 'ID: {id}', number: 'Item {number}', size: 'Size: {size}', ext: 'Extension: {ext}' },
      placeholder: '',
      pasteAndDragAndDropSupportRule: 'You can (hover & paste) or (drag & drop) files here',
      pasteSupportRule: 'Hover & paste files here',
      dragAndDropSupportRule: 'Drag and drop files here',
    },
  },
  // Hooks
  // Components
  button: {
    defaultType: 'button',
    defaultColor: 'info',
    defaultLoadingTitle: 'Loading',
    colors: {
      fill: {
        success: { background: 'bg-success', border: 'border-success', text: 'text-white' },
        error: { background: 'bg-error', border: 'border-error', text: 'text-white' },
        warning: { background: 'bg-warning', border: 'border-warning', text: 'text-white' },
        info: { background: 'bg-info', border: 'border-info', text: 'text-white' },
      },
      outline: {
        success: { border: 'border-success', text: 'text-success' },
        error: { border: 'border-error', text: 'text-error' },
        warning: { border: 'border-warning', text: 'text-warning' },
        info: { border: 'border-info', text: 'text-info' },
      },
      text: {
        success: { text: 'text-success' },
        error: { text: 'text-error' },
        warning: { text: 'text-warning' },
        info: { text: 'text-info' },
      },
    },
    corners: {
      small: ['rounded'],
      default: ['rounded-md'],
      large: ['rounded-xl'],
      circle: ['rounded-full'],
      sharp: ['rounded-none'],
      full: ['rounded-full'],
    },
    sizes: {
      tiny: {
        fill: {
          textSize: ['text-sm'],
          textWeight: ['font-medium'],
          gap: ['gap-1'],
          padding: ['px-2', 'py-1'],
        },
        text: {
          textSize: ['text-base'],
          textWeight: ['font-medium'],
          gap: ['gap-1'],
          padding: ['px-2', 'py-1'],
        },
        outline: {
          textSize: ['text-sm'],
          textWeight: ['font-medium'],
          gap: ['gap-1'],
          padding: ['px-2', 'py-1'],
        },
      },
      small: {
        fill: {
          textSize: ['text-sm'],
          textWeight: ['font-medium'],
          gap: ['gap-1'],
          padding: ['px-3', 'py-2'],
        },
        text: {
          textSize: ['text-base'],
          textWeight: ['font-medium'],
          gap: ['gap-1'],
          padding: ['px-3', 'py-2'],
        },
        outline: {
          textSize: ['text-sm'],
          textWeight: ['font-medium'],
          gap: ['gap-1'],
          padding: ['px-3', 'py-2'],
        },
      },
      default: {
        fill: {
          textSize: ['text-lg'],
          textWeight: ['font-medium'],
          gap: ['gap-2'],
          padding: ['px-3', 'py-2'],
        },
        text: {
          textSize: ['text-lg'],
          textWeight: ['font-medium'],
          gap: ['gap-2'],
          padding: ['px-3', 'py-2'],
        },
        outline: {
          textSize: ['text-lg'],
          textWeight: ['font-medium'],
          gap: ['gap-2'],
          padding: ['px-3', 'py-2'],
        },
      },
      large: {
        fill: {
          textSize: ['text-xl'],
          textWeight: ['font-medium'],
          gap: ['gap-3'],
          padding: ['p-3'],
        },
        text: {
          textSize: ['text-xl'],
          textWeight: ['font-medium'],
          gap: ['gap-3'],
          padding: ['p-3'],
        },
        outline: {
          textSize: ['text-xl'],
          textWeight: ['font-medium'],
          gap: ['gap-3'],
          padding: ['p-3'],
        },
      },
      larger: {
        fill: {
          textSize: ['text-xl'],
          textWeight: ['font-medium'],
          gap: ['gap-4'],
          padding: ['p-4'],
        },
        text: {
          textSize: ['text-xl'],
          textWeight: ['font-medium'],
          gap: ['gap-4'],
          padding: ['p-4'],
        },
        outline: {
          textSize: ['text-xl'],
          textWeight: ['font-medium'],
          gap: ['gap-4'],
          padding: ['p-4'],
        },
      },
      huge: {
        fill: {
          textSize: ['text-2xl'],
          textWeight: ['font-medium'],
          gap: ['gap-4'],
          padding: ['p-4'],
        },
        text: {
          textSize: ['text-2xl'],
          textWeight: ['font-medium'],
          gap: ['gap-4'],
          padding: ['p-4'],
        },
        outline: {
          textSize: ['text-2xl'],
          textWeight: ['font-medium'],
          gap: ['gap-4'],
          padding: ['p-4'],
        },
      },
      extreme: {
        fill: {
          textSize: ['text-2xl'],
          textWeight: ['font-medium'],
          gap: ['gap-5'],
          padding: ['p-5'],
        },
        text: {
          textSize: ['text-2xl'],
          textWeight: ['font-medium'],
          gap: ['gap-5'],
          padding: ['p-5'],
        },
        outline: {
          textSize: ['text-2xl'],
          textWeight: ['font-medium'],
          gap: ['gap-5'],
          padding: ['p-5'],
        },
      },
    },
  },
  breadcrumbs: { defaultSeparator: '|' },
  form: {
    label: {
      as: 'label',
      showRequiredIndicator: true,
      className: 'flex-nowrap items-center text-xs font-medium text-title-2 gap-1',
      stateSharedClassName:
        'absolute flex-nowrap items-center origin-left z-25 rtl:origin-right rounded transition-all duration-300 ease-in-out',
      inactiveClassName: 'inset-px scale-100 px-3 pointer-events-none',
      activeClassName: 'top-0 inset-s-3 translate-y-[-50%] scale-90 max-w-[calc(100%-0.5rem)] px-1.5 py-px',
    },
    fieldset: { className: 'text-title-2 [&_label]:bg-[inherit]' },
    textfield: { className: 'text-sm placeholder:text-body-3' },
    textarea: { className: 'text-sm placeholder:text-body-3', defaultRows: 2 },
    searchField: { clearIcon: '🗙', searchIcon: '🔎︎' },
    select: {
      triggerIcon: '⮟',
      optionClassName: 'bg-main hover:bg-third',
      optionGroupClassName: 'bg-main hover:bg-third',
    },
    check: { color: 'text-', activeColor: 'text-success' },
    password: {
      useLength: true,
      length: 8,
      maxLength: undefined,
      useLowercase: true,
      lowercaseLength: 1,
      useUppercase: true,
      uppercaseLength: 1,
      useNumbers: true,
      numbersLength: 1,
      useSpecialChars: true,
      specialCharsLength: 1,
      hasCopy: true,
      hasGenerate: false,
      hasShow: true,
      hasValidation: false,
      showValidationProgress: true,
      showValidationsList: false,
      colors: {
        0: { textColor: 'text-error', progressColor: 'bg-error' },
        20: { textColor: 'text-error', progressColor: 'bg-error' },
        40: { textColor: 'text-warning', progressColor: 'bg-warning' },
        60: { textColor: 'text-info', progressColor: 'bg-info' },
        80: { textColor: 'text-primary', progressColor: 'bg-primary' },
        100: { textColor: 'text-success', progressColor: 'bg-success' },
      },
      invalidIcon: '✘',
      validIcon: '✔',
      showIcon: '👁',
      hideIcon: '⊘',
      confirmMainIcon: '🔒︎',
      confirmingMainIcon: 'ᗢ',
      copyIcon: '🗐',
    },
    otp: { length: 6, className: 'rounded-xl text-center text-xl font-bold text-title-1' },
    range: { step: 1, showMinMax: true, showValue: true, valuePrefix: '', valueSuffix: '', className: 'text-sm' },
    phone: {
      worldwide: true,
      codePrefix: '+',
      showCountriesName: true,
      selectedCountriesOnly: [],
      showCountriesFlags: true,
    },
    autoComplete: {
      triggerIcon: '⮟',
      triggerWrapperClassName: 'text-sm',
      multiple: false,
      searchable: true,
      searchViaLabel: true,
      showClearSearch: true,
      ClearSearchIcon: '🗙',
      multipleTagsCloseIcon: '🗙',
    },
    uploader: {
      defaultFileCategory: ['all'],
      onDetectErrors: () => {},
      minBlockHeight: 'min-h-[100px]',
      showProgress: true,
      progressColor: 'text-primary',
      allowDragAndDrop: true,
      allowPaste: true,
      minFiles: 1,
      maxFiles: undefined,
      minSize: undefined,
      maxSize: 5,
      minFilesSize: undefined,
      maxFilesSize: undefined,
      fileIcon: '🗎',
      filesIcon: '🗐',
      imageIcon: '⛶',
      imagesIcon: '⛶',
      videoIcon: '▷',
      videosIcon: '▷',
      audioIcon: '♫',
      audiosIcon: '♫',
      textIcon: '🗎',
      textsIcon: '🗐',
      applicationIcon: '■',
      applicationsIcon: '■',
      executableIcon: '■',
      executablesIcon: '■',
    },
  },
  // Others
  LinkType: 'a',
  settings: { isRtl: false, locale: 'en' },
}

export { defaultConfig }
