export type ComponentGroup = 'UI' | 'Form fields' | 'Form composition' | 'Partials' | 'Helpers'

export type ComponentDoc = {
  slug: string
  name: string
  group: ComponentGroup
  summary: string
  description: string
  importName: string
  demo: string
  code: string
  props: { name: string; type: string; defaultValue: string; description: string }[]
  notes: string[]
}

export const componentGroups: ComponentGroup[] = ['UI', 'Form fields', 'Form composition', 'Partials', 'Helpers']

export const componentCatalog: ComponentDoc[] = [
  {
    slug: 'accordion',
    name: 'Accordion',
    group: 'UI',
    summary: 'Animated disclosure section for progressively revealed content.',
    description:
      'A locally controlled disclosure section with an accessible title trigger and animated content region.',
    importName: 'Accordion',
    demo: 'accordion',
    code: `<Accordion title="Account details" initialCollapsed>\n  <p>Content appears when the section is expanded.</p>\n</Accordion>`,
    props: [
      {
        name: 'title',
        type: 'ReactNode',
        defaultValue: '—',
        description: 'Trigger title displayed at the top of the section.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        defaultValue: 'required',
        description: 'Content revealed by expanding the section.',
      },
      {
        name: 'initialCollapsed',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Initial collapsed state; component manages subsequent toggles locally.',
      },
      {
        name: 'setOpen',
        type: '(collapsed: boolean) => void',
        defaultValue: '—',
        description: 'Notifies when the title trigger toggles.',
      },
      {
        name: 'allTitleClickable',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Makes the whole title area the disclosure button.',
      },
      { name: 'condition', type: 'boolean', defaultValue: 'true', description: 'Returns null when false.' },
    ],
    notes: [
      'Use a concise title that describes the hidden content.',
      'With allTitleClickable=false, only the chevron is interactive.',
    ],
  },
  {
    slug: 'button',
    name: 'Button',
    group: 'UI',
    summary: 'Semantic action and navigation control with variant, size, and loading states.',
    description:
      'A themed button/link primitive with semantic colors, icon composition, tooltips, and loading presentation.',
    importName: 'Button',
    demo: 'button',
    code: `<Button color="info" variant="fill" onClick={() => setClicked(true)}>\n  Save changes\n</Button>`,
    props: [
      {
        name: 'variant',
        type: "'fill' | 'outline' | 'text' | 'none'",
        defaultValue: "'fill'",
        description: 'Visual treatment for the action.',
      },
      {
        name: 'color',
        type: 'semantic color',
        defaultValue: 'config default',
        description: 'Theme color token such as info, primary, success, or second.',
      },
      {
        name: 'size',
        type: 'tiny … extreme | none',
        defaultValue: "'default'",
        description: 'Size preset from shared configuration.',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Replaces regular content with loader content; does not disable the button.',
      },
      {
        name: 'href',
        type: 'string',
        defaultValue: '—',
        description: 'Renders a navigation link instead of a native button.',
      },
      {
        name: 'onClick',
        type: 'MouseEvent handler',
        defaultValue: '—',
        description: 'Action handler for buttons and links.',
      },
      { name: 'condition', type: 'boolean', defaultValue: 'true', description: 'Returns null when false.' },
    ],
    notes: [
      'Use type="submit" to submit a form; the default type is button.',
      'Loading changes content but does not disable the control.',
    ],
  },
  {
    slug: 'dialog',
    name: 'Dialog',
    group: 'UI',
    summary: 'Modal surface with overlay, positioning, portal, and close behavior.',
    description:
      'A dialog primitive driven by open/show state and setter callbacks, with optional portal rendering and placement controls.',
    importName: 'Dialog',
    demo: 'dialog',
    code: `<Dialog open={open} setOpen={setOpen} show={show} setShow={setShow}>\n  <div className="p-6">Dialog content</div>\n</Dialog>`,
    props: [
      {
        name: 'open',
        type: 'boolean',
        defaultValue: 'required',
        description: 'Whether the dialog is interactive/open.',
      },
      {
        name: 'setOpen',
        type: '(open: boolean) => void',
        defaultValue: 'required',
        description: 'Updates the open state.',
      },
      {
        name: 'show',
        type: 'boolean',
        defaultValue: 'required',
        description: 'Controls whether the dialog is mounted/shown for its transition.',
      },
      {
        name: 'setShow',
        type: '(show: boolean) => void',
        defaultValue: 'required',
        description: 'Updates the show state.',
      },
      {
        name: 'position',
        type: "'center' | 'top' | 'bottom' | 'start' | 'end'",
        defaultValue: "'center'",
        description: 'Dialog placement.',
      },
      { name: 'usePortal', type: 'boolean', defaultValue: 'true', description: 'Renders into a portal when enabled.' },
    ],
    notes: [
      'Use the open and show state pair together to manage transitions.',
      'Escape and overlay interactions are enabled by default.',
    ],
  },
  {
    slug: 'digit',
    name: 'Digit',
    group: 'UI',
    summary: 'Locale-aware numeric display for prices, counts, and measurements.',
    description:
      'Formats a numeric value using currency, precision, unit, locale, and sign options from the shared number utilities.',
    importName: 'Digit',
    demo: 'digit',
    code: `<Digit value={12845.75} decimalsMin={2} decimalsMax={2} endUnit="USD" />`,
    props: [
      { name: 'value', type: 'number | string', defaultValue: 'required', description: 'Numeric amount to format.' },
      { name: 'decimalsMin', type: 'number', defaultValue: 'config default', description: 'Minimum fraction digits.' },
      { name: 'decimalsMax', type: 'number', defaultValue: 'config default', description: 'Maximum fraction digits.' },
      {
        name: 'startUnit / endUnit',
        type: 'ReactNode',
        defaultValue: '—',
        description: 'Optional content before or after the formatted number.',
      },
      { name: 'currency', type: 'currency options', defaultValue: '—', description: 'Currency display configuration.' },
    ],
    notes: [
      'Use the UseDigit helper when you need a formatted string instead of a component.',
      'Prefer explicit precision for financial values.',
    ],
  },
  {
    slug: 'dropdown',
    name: 'Dropdown',
    group: 'UI',
    summary: 'Button-anchored menu with outside-close handling and placement options.',
    description: 'A locally controlled menu that passes a close callback to its render-prop children.',
    importName: 'Dropdown',
    demo: 'dropdown',
    code: `<Dropdown trigger="More actions" staticPosition position="BOTTOM_START">\n  {(close) => <button onClick={close}>Choose action</button>}\n</Dropdown>`,
    props: [
      { name: 'trigger', type: 'ReactNode', defaultValue: 'required', description: 'Content for the trigger button.' },
      {
        name: 'children',
        type: '(close: () => void) => ReactNode',
        defaultValue: 'required',
        description: 'Menu render function with a close callback.',
      },
      {
        name: 'staticPosition',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Uses the position token rather than calculated viewport position.',
      },
      { name: 'position', type: 'placement token', defaultValue: "'TOP_START'", description: 'Static menu placement.' },
      {
        name: 'menuClassName',
        type: 'string',
        defaultValue: 'w-56 …',
        description: 'Classes applied to the menu surface.',
      },
      {
        name: 'onToggle',
        type: '(opened: boolean) => void',
        defaultValue: '—',
        description: 'Notifies when the menu opens or closes.',
      },
    ],
    notes: ['Closes on outside mouse/touch starts.', 'Menu children should provide their own keyboard semantics.'],
  },
  {
    slug: 'flag',
    name: 'Flag',
    group: 'UI',
    summary: 'Country flag image with an error fallback and configurable dimensions.',
    description:
      'Loads a static country SVG from /flags/{CODE}.svg and shows a country-code fallback if loading fails.',
    importName: 'Flag',
    demo: 'flag',
    code: `<Flag country="OM" size={32} ratio="3x2" />`,
    props: [
      {
        name: 'country',
        type: 'CountryType',
        defaultValue: 'required',
        description: 'Country code used to construct the SVG path.',
      },
      { name: 'size', type: 'number', defaultValue: '20', description: 'Image wrapper width in pixels.' },
      { name: 'ratio', type: "'3x2' | '1x1'", defaultValue: "'3x2'", description: 'Width-to-height ratio.' },
      {
        name: 'fallback',
        type: 'ReactNode',
        defaultValue: 'uppercase country code',
        description: 'Fallback content shown after image failure.',
      },
      {
        name: 'setIsExist',
        type: '(exists: boolean) => void',
        defaultValue: '—',
        description: 'Notified on image load or error.',
      },
    ],
    notes: [
      'Static flags must be available at /flags/{uppercase code}.svg.',
      'The playground syncs library flags into its public directory before dev/build.',
    ],
  },
  {
    slug: 'breadcrumbs',
    name: 'Breadcrumbs',
    group: 'UI',
    summary: 'Compact hierarchical navigation trail with active item styling.',
    description: 'Renders a sequence of breadcrumb items using the shared Button navigation primitive.',
    importName: 'Breadcrumbs',
    demo: 'breadcrumbs',
    code: `<Breadcrumbs items={[\n  { title: 'Library', href: '/' },\n  { title: 'Components', href: '/components' },\n  { title: 'Button', active: true },\n]} />`,
    props: [
      { name: 'items', type: 'BreadcrumbProps[]', defaultValue: 'required', description: 'Ordered navigation items.' },
      { name: 'separator', type: 'ReactNode', defaultValue: 'config default', description: 'Content between items.' },
      {
        name: 'className',
        type: 'string',
        defaultValue: '—',
        description: 'Classes applied to the breadcrumb wrapper.',
      },
    ],
    notes: ['Mark the current page active and omit its href.', 'Keep the hierarchy short enough to scan.'],
  },
  {
    slug: 'copyrights',
    name: 'Copyrights',
    group: 'UI',
    summary: 'Small copyright and sponsor attribution line.',
    description: 'Renders a year range, copyright holder, optional sponsor link, and customizable trailing content.',
    importName: 'Copyrights',
    demo: 'copyrights',
    code: `<Copyrights startYear={2024} sponsor="Bhoenix Studio" copyrights=" · Crafted for the web" />`,
    props: [
      {
        name: 'startYear',
        type: 'number',
        defaultValue: 'current year',
        description: 'First year in the displayed range.',
      },
      { name: 'sponsor', type: 'string', defaultValue: '—', description: 'Optional sponsor label.' },
      { name: 'sponsorLink', type: 'string', defaultValue: '—', description: 'Optional sponsor URL.' },
      {
        name: 'copyrights',
        type: 'ReactNode',
        defaultValue: 'config default',
        description: 'Additional attribution content.',
      },
    ],
    notes: ['Use a real sponsor destination in production.', 'Native paragraph attributes are forwarded.'],
  },
  {
    slug: 'loader',
    name: 'Loader',
    group: 'Partials',
    summary: 'Animated skeleton blocks for loading and placeholder layouts.',
    description: 'Renders one or more skeleton blocks with rounded, circle, square, sharp, or text treatments.',
    importName: 'Loader',
    demo: 'loader',
    code: `<Loader variant="text" counts={3} height="1rem" width="14rem" wrapperClassName="gap-2" />`,
    props: [
      {
        name: 'height',
        type: 'number | string',
        defaultValue: 'required',
        description: 'Height of each skeleton block.',
      },
      { name: 'width', type: 'number | string', defaultValue: "'100%'", description: 'Width of each skeleton block.' },
      { name: 'counts', type: 'number', defaultValue: '1', description: 'Number of blocks to render.' },
      {
        name: 'variant',
        type: "'rounded' | 'circle' | 'sharp' | 'square' | 'text'",
        defaultValue: "'rounded'",
        description: 'Skeleton shape and layout.',
      },
      { name: 'duration', type: 'number', defaultValue: '2.5', description: 'Pulse animation duration in seconds.' },
    ],
    notes: [
      'Mirror the real component’s layout to reduce layout shift.',
      'Respect reduced-motion preferences in surrounding animated content.',
    ],
  },
  {
    slug: 'progress-bar',
    name: 'ProgressBar',
    group: 'Partials',
    summary: 'Progress visualization with optional label and value text.',
    description: 'Displays a value relative to an upper bound and can include a label and accessible textual value.',
    importName: 'ProgressBar',
    demo: 'progress-bar',
    code: `<ProgressBar value={7} outOf={10} showValueAsText label="Build progress" />`,
    props: [
      { name: 'value', type: 'number', defaultValue: 'required', description: 'Current progress amount.' },
      { name: 'outOf', type: 'number', defaultValue: '100', description: 'Maximum progress amount.' },
      { name: 'label', type: 'ReactNode', defaultValue: '—', description: 'Optional visible progress label.' },
      { name: 'showValueAsText', type: 'boolean', defaultValue: 'false', description: 'Shows the progress as text.' },
      {
        name: 'barColor',
        type: 'string',
        defaultValue: 'config default',
        description: 'Tailwind class for the filled bar.',
      },
    ],
    notes: [
      'Keep progress values within the intended range.',
      'Provide a label when progress meaning is not obvious from context.',
    ],
  },
  {
    slug: 'label',
    name: 'Label',
    group: 'Form fields',
    summary: 'Reusable label primitive with required state and forwarded label attributes.',
    description: 'A label element intended for composition with form inputs or as a standalone field label.',
    importName: 'Label',
    demo: 'label',
    code: `<Label required>Email address</Label>`,
    props: [
      { name: 'children', type: 'ReactNode', defaultValue: '—', description: 'Visible label content.' },
      {
        name: 'required',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Displays the configured required indicator.',
      },
      {
        name: 'className',
        type: 'string',
        defaultValue: 'config default',
        description: 'Classes applied to the label.',
      },
      {
        name: 'attributes',
        type: 'LabelHTMLAttributes',
        defaultValue: '—',
        description: 'Native label attributes, including htmlFor.',
      },
    ],
    notes: [
      'Connect standalone labels to controls using htmlFor and id.',
      'Prefer visible labels over placeholder-only identification.',
    ],
  },
  {
    slug: 'input-helper',
    name: 'InputHelper',
    group: 'Form fields',
    summary: 'Helper or error message primitive for form inputs.',
    description: 'A small message element that supports normal helper and semantic error presentations.',
    importName: 'InputHelper',
    demo: 'input-helper',
    code: `<InputHelper>Use at least 12 characters.</InputHelper>\n<InputHelper asError role="alert">This value is required.</InputHelper>`,
    props: [
      { name: 'children', type: 'ReactNode', defaultValue: '—', description: 'Helper or validation message.' },
      {
        name: 'asError',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Applies the configured error text treatment.',
      },
      {
        name: 'className',
        type: 'string',
        defaultValue: 'config default',
        description: 'Classes applied to the message element.',
      },
    ],
    notes: [
      'Place an error message near the field it describes.',
      'Use role="alert" when an error must be announced immediately.',
    ],
  },
  {
    slug: 'text-field',
    name: 'TextField',
    group: 'Form fields',
    summary: 'Controlled text input with label, helper, prefix, suffix, and validation states.',
    description:
      'The base text input used directly or through Input/Form. Pass native input attributes through properties.',
    importName: 'TextField',
    demo: 'text-field',
    code: `<TextField label="Display name" properties={{ value, onChange: (event) => setValue(event.target.value) }} />`,
    props: [
      { name: 'label', type: 'ReactNode | LabelProps', defaultValue: "''", description: 'Field label.' },
      {
        name: 'properties.value',
        type: 'string | number | readonly string[]',
        defaultValue: "''",
        description: 'Controlled field value.',
      },
      {
        name: 'properties.onChange',
        type: 'ChangeEvent handler',
        defaultValue: '—',
        description: 'Receives native input change events.',
      },
      { name: 'inputHelper', type: 'ReactNode', defaultValue: '—', description: 'Supporting field description.' },
      {
        name: 'error / errorHelper',
        type: 'boolean / ReactNode',
        defaultValue: 'false / —',
        description: 'Enables the error border and message.',
      },
      {
        name: 'prefix / suffix',
        type: 'ReactNode',
        defaultValue: '—',
        description: 'Content around the input inside its wrapper.',
      },
    ],
    notes: [
      'Use value and onChange together for controlled input behavior.',
      'Native input attributes are passed inside properties.',
    ],
  },
  {
    slug: 'search-field',
    name: 'SearchField',
    group: 'Form fields',
    summary: 'Text input with search, clear, and keyboard callbacks.',
    description:
      'Composes TextField with search and clear affordances. Supports controlled native input props and search-specific callbacks.',
    importName: 'SearchField',
    demo: 'search-field',
    code: `<SearchField label="Search docs" properties={{\n  value, onChange: (event) => setValue(event.target.value),\n  onSearch: setSubmittedQuery,\n}} />`,
    props: [
      {
        name: 'properties.value / onChange',
        type: 'native input props',
        defaultValue: "'' / —",
        description: 'Controlled search field state.',
      },
      {
        name: 'properties.onSearch',
        type: '(value: string) => void',
        defaultValue: '—',
        description: 'Called by the search action button.',
      },
      {
        name: 'properties.onEnter',
        type: '(value: string) => void',
        defaultValue: '—',
        description: 'Called when Enter is pressed.',
      },
      {
        name: 'properties.onClear',
        type: '(clearedValue: string) => void',
        defaultValue: '—',
        description: 'Called after the clear action.',
      },
      {
        name: 'showSearchIcon / showClearIcon',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Shows the corresponding actions.',
      },
    ],
    notes: [
      'onSearch is action-driven; keep onChange for typing state.',
      'A clear action dispatches a native input event to update controlled parents.',
    ],
  },
  {
    slug: 'textarea-field',
    name: 'TextareaField',
    group: 'Form fields',
    summary: 'Controlled multiline text input with shared field styling.',
    description:
      'A textarea counterpart to TextField with the same label, helper, error, and wrapper composition patterns.',
    importName: 'TextareaField',
    demo: 'textarea-field',
    code: `<TextareaField label="Description" properties={{\n  value, onChange: (event) => setValue(event.target.value), rows: 4,\n}} />`,
    props: [
      { name: 'label', type: 'ReactNode | LabelProps', defaultValue: "''", description: 'Field label.' },
      {
        name: 'properties.value / onChange',
        type: 'textarea value and change event',
        defaultValue: "'' / —",
        description: 'Controlled text state.',
      },
      { name: 'properties.rows', type: 'number', defaultValue: 'config default', description: 'Visible line count.' },
      { name: 'inputHelper', type: 'ReactNode', defaultValue: '—', description: 'Supporting field description.' },
      {
        name: 'error / errorHelper',
        type: 'boolean / ReactNode',
        defaultValue: 'false / —',
        description: 'Error presentation and explanation.',
      },
    ],
    notes: ['Set rows to match expected content length.', 'Native textarea attributes belong in properties.'],
  },
  {
    slug: 'select',
    name: 'Select',
    group: 'Form fields',
    summary: 'Styled select control with option groups and controlled selection.',
    description:
      'Renders a native select with Loomora field styling, optional trigger decoration, and custom option records.',
    importName: 'Select',
    demo: 'select',
    code: `<Select label="Country" options={countries} properties={{\n  value, onChange: (event) => setValue(event.target.value),\n}} />`,
    props: [
      {
        name: 'options',
        type: 'SelectOption[]',
        defaultValue: '[]',
        description: 'Native option records or optgroup records.',
      },
      {
        name: 'properties.value / onChange',
        type: 'select value and change event',
        defaultValue: "'' / —",
        description: 'Controlled selection.',
      },
      {
        name: 'showTrigger',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Shows the configured select trigger.',
      },
      {
        name: 'trigger',
        type: 'ReactNode | icon config',
        defaultValue: 'config default',
        description: 'Custom trigger content or icon settings.',
      },
      {
        name: 'label / error / inputHelper',
        type: 'field composition props',
        defaultValue: '—',
        description: 'Shared field label, error and helper options.',
      },
    ],
    notes: ['Use value and onChange for controlled selections.', 'Option values should remain stable and unique.'],
  },
  {
    slug: 'check-field',
    name: 'CheckField',
    group: 'Form fields',
    summary: 'Checkbox, radio, and switch controls with checked state.',
    description: 'A stylized check control that supports checkbox, radio, and switch modes with native input events.',
    importName: 'CheckField',
    demo: 'check-field',
    code: `<CheckField label="Enable updates" properties={{\n  type: 'checkbox', checked, onChange: (event) => setChecked(event.target.checked),\n}} />`,
    props: [
      {
        name: 'properties.type',
        type: "'checkbox' | 'radio' | 'switch'",
        defaultValue: "'checkbox'",
        description: 'Visual and semantic control type.',
      },
      { name: 'properties.checked', type: 'boolean', defaultValue: '—', description: 'Controlled checked state.' },
      {
        name: 'properties.onChange',
        type: 'ChangeEvent handler',
        defaultValue: '—',
        description: 'Receives the native input change event.',
      },
      {
        name: 'color / activeColor',
        type: 'semantic text color',
        defaultValue: 'config defaults',
        description: 'Unchecked and selected colors.',
      },
      {
        name: 'label / inputHelper / error',
        type: 'field composition props',
        defaultValue: '—',
        description: 'Label and field feedback.',
      },
    ],
    notes: [
      'Use checked and onChange, not value, for controlled checks.',
      'Use a shared name and distinct values when composing radio groups.',
    ],
  },
  {
    slug: 'otp-field',
    name: 'OtpField',
    group: 'Form fields',
    summary: 'Controlled one-time-code entry split across digit cells.',
    description: 'Renders a fixed-length sequence of digit inputs with paste distribution and keyboard focus movement.',
    importName: 'OtpField',
    demo: 'otp-field',
    code: `<OtpField label="Verification code" length={6} properties={{ value, onChange: setValue }} />`,
    props: [
      { name: 'length', type: 'number', defaultValue: 'config default', description: 'Number of digit cells.' },
      { name: 'properties.value', type: 'string[]', defaultValue: '[]', description: 'Controlled digit array.' },
      {
        name: 'properties.onChange',
        type: 'Dispatch<SetStateAction<string[]>>',
        defaultValue: '—',
        description: 'Receives the updated digit array.',
      },
      {
        name: 'properties.autoFocus',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Focuses the first cell on mount.',
      },
      {
        name: 'properties.disabled / required',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Native input states.',
      },
    ],
    notes: [
      'Paste distributes numeric characters across available cells.',
      'Keep the controlled array synchronized with the component callback.',
    ],
  },
  {
    slug: 'password-field',
    name: 'PasswordField',
    group: 'Form fields',
    summary: 'Password input with generation, visibility, copy, and validation features.',
    description:
      'Composes a text field with password visibility, optional generation and copy actions, and strength validation.',
    importName: 'PasswordField',
    demo: 'password-field',
    code: `<PasswordField label="Password" hasShow hasGenerate hasValidation\n  properties={{ value, onChange: (event) => setValue(event.target.value) }}\n  onGenerate={setValue} />`,
    props: [
      {
        name: 'properties.value / onChange',
        type: 'native input props',
        defaultValue: "'' / —",
        description: 'Controlled password value.',
      },
      {
        name: 'hasShow / hasCopy',
        type: 'boolean',
        defaultValue: 'config defaults',
        description: 'Enables visibility and copy actions.',
      },
      {
        name: 'hasGenerate',
        type: 'boolean',
        defaultValue: 'config default',
        description: 'Adds a generate-password action.',
      },
      {
        name: 'onGenerate',
        type: '(password: string) => void',
        defaultValue: '—',
        description: 'Receives the generated password.',
      },
      {
        name: 'hasValidation',
        type: 'boolean',
        defaultValue: 'config default',
        description: 'Enables validation feedback.',
      },
      {
        name: 'validationSettings',
        type: 'PasswordValidationProps',
        defaultValue: 'config defaults',
        description: 'Controls required character types and lengths.',
      },
    ],
    notes: [
      'For controlled inputs, update value from onChange and onGenerate.',
      'Generation is random and should be triggered by the user.',
    ],
  },
  {
    slug: 'phone-input',
    name: 'PhoneInput',
    group: 'Form fields',
    summary: 'Country-aware phone entry with parsing and formatting callbacks.',
    description:
      'Combines country calling-code selection, country metadata, and a text field into a structured phone input.',
    importName: 'PhoneInput',
    demo: 'phone-input',
    code: `<PhoneInput label="Phone" properties={{\n  defaultCountry: 'OM', value, setValue: ({ value }) => setValue(value),\n}} />`,
    props: [
      { name: 'properties.value', type: 'string', defaultValue: '—', description: 'Controlled local phone number.' },
      {
        name: 'properties.setValue',
        type: '(phone: PhoneValue) => void',
        defaultValue: '—',
        description: 'Receives structured country code and phone values.',
      },
      {
        name: 'properties.defaultCountry',
        type: 'CountryType',
        defaultValue: '—',
        description: 'Initial country calling code.',
      },
      {
        name: 'properties.country',
        type: 'CountryType',
        defaultValue: '—',
        description: 'Controlled selected country.',
      },
      {
        name: 'worldwide',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Allows selecting from the worldwide country list.',
      },
      {
        name: 'showCountriesName / showCountriesFlags',
        type: 'boolean',
        defaultValue: 'true',
        description: 'Controls country option decorations.',
      },
    ],
    notes: [
      'setValue receives an object with local value and final formatted number.',
      'Use country to control selection and onCountryChange to observe it.',
    ],
  },
  {
    slug: 'range-field',
    name: 'RangeField',
    group: 'Form fields',
    summary: 'Custom range slider with marks, value display, and controlled state.',
    description:
      'A range control that renders its own track and thumb presentation while exposing a controlled numeric value.',
    importName: 'RangeField',
    demo: 'range-field',
    code: `<RangeField label="Volume" properties={{ value, setValue, min: 0, max: 100, showValue: true }} />`,
    props: [
      { name: 'properties.value', type: 'number', defaultValue: '0', description: 'Current numeric value.' },
      {
        name: 'properties.setValue',
        type: '(value: number) => void',
        defaultValue: '—',
        description: 'Required callback for controlled updates.',
      },
      { name: 'properties.min / max', type: 'number', defaultValue: '0 / 0', description: 'Slider bounds.' },
      {
        name: 'properties.step',
        type: 'number',
        defaultValue: 'config default',
        description: 'Increment between values.',
      },
      {
        name: 'properties.marks',
        type: 'RangeMark[]',
        defaultValue: '[]',
        description: 'Optional labeled points on the track.',
      },
      {
        name: 'showValue / showMinMax',
        type: 'boolean',
        defaultValue: 'config defaults',
        description: 'Shows value and endpoint labels.',
      },
    ],
    notes: [
      'Both value and setValue are part of the component contract.',
      'Clamp values to the declared min/max range in parent state.',
    ],
  },
  {
    slug: 'autocomplete',
    name: 'Autocomplete',
    group: 'Form fields',
    summary: 'Searchable single- or multi-select option picker.',
    description:
      'An accessible combobox-style picker with configurable options, selected values, search, and multi-selection limits.',
    importName: 'Autocomplete',
    demo: 'autocomplete',
    code: `<Autocomplete label="Choose a component" options={options} properties={{\n  value, onChange: (next) => setValue(String(next ?? '')),\n}} />`,
    props: [
      { name: 'options', type: 'AutocompleteOption[]', defaultValue: '[]', description: 'Selectable option records.' },
      {
        name: 'properties.value',
        type: 'string | number | array',
        defaultValue: '—',
        description: 'Current selected value(s).',
      },
      {
        name: 'properties.onChange',
        type: 'callback',
        defaultValue: 'required',
        description: 'Receives selected value(s) and selected option(s).',
      },
      {
        name: 'properties.multiple',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Enables multi-select mode.',
      },
      {
        name: 'properties.searchable / onSearch',
        type: 'boolean / callback',
        defaultValue: 'false / —',
        description: 'Enables option filtering and search updates.',
      },
      {
        name: 'properties.min / max',
        type: 'number',
        defaultValue: '—',
        description: 'Selection count constraints in multiple mode.',
      },
    ],
    notes: [
      'Single mode uses one scalar value; multiple mode uses an array.',
      'Use renderValue/renderOption when options need custom visual composition.',
    ],
  },
  {
    slug: 'uploader-field',
    name: 'UploaderField',
    group: 'Form fields',
    summary: 'Controlled file picker with validation, drag/drop, paste, and preview layouts.',
    description:
      'An upload surface that validates files and renders selected files using thumbnail, list, background, or profile-picture layouts.',
    importName: 'UploaderField',
    demo: 'uploader-field',
    code: `<UploaderField label="Attachments" properties={{\n  multiple: true, value: files, onChange: (next) => setFiles(next),\n  accept: ['image', '.pdf'], maxFiles: 3, viewType: 'list',\n}} />`,
    props: [
      {
        name: 'properties.multiple',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Enables single or multiple file mode.',
      },
      {
        name: 'properties.value',
        type: 'FileProps | FileProps[]',
        defaultValue: '—',
        description: 'Controlled preview record(s).',
      },
      {
        name: 'properties.onChange',
        type: 'callback',
        defaultValue: '—',
        description: 'Receives preview records, native files, and validity.',
      },
      {
        name: 'properties.accept',
        type: 'FileExtType[]',
        defaultValue: 'config default',
        description: 'Accepted extensions or file categories.',
      },
      {
        name: 'properties.viewType',
        type: 'UploaderFieldViewType',
        defaultValue: 'background / thumbs',
        description: 'Preview layout style.',
      },
      {
        name: 'properties.maxFiles / maxSize',
        type: 'number',
        defaultValue: 'config defaults',
        description: 'File count and size constraints.',
      },
    ],
    notes: [
      'File inputs cannot be assigned programmatically; value controls preview records, not the native file input.',
      'Keep the parent preview state updated from onChange.',
    ],
  },
  {
    slug: 'text-editor',
    name: 'TextEditor',
    group: 'Form fields',
    summary: 'TinyMCE rich-text editor with controlled content and configurable toolbar.',
    description:
      'A rich text input that wraps TinyMCE React, with value/change callbacks and editor initialization options.',
    importName: 'TextEditor',
    demo: 'text-editor',
    code: `<TextEditor label="Article body" properties={{\n  value, onChange: setValue, height: 320, toolbar: 'bold italic | bullist numlist',\n}} />`,
    props: [
      {
        name: 'properties.value / onChange',
        type: 'string / (content: string) => void',
        defaultValue: '—',
        description: 'Controlled HTML content.',
      },
      {
        name: 'properties.initialValue',
        type: 'string',
        defaultValue: '—',
        description: 'Initial content for uncontrolled usage.',
      },
      { name: 'properties.height', type: 'number | string', defaultValue: '420', description: 'Editor height.' },
      {
        name: 'properties.plugins / toolbar',
        type: 'TinyMCE options',
        defaultValue: 'configured defaults',
        description: 'Editor plugin and toolbar setup.',
      },
      {
        name: 'properties.disabled / required',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Editor interaction and required states.',
      },
      {
        name: 'onBlur',
        type: '(content: string) => void',
        defaultValue: '—',
        description: 'Receives editor content on blur.',
      },
    ],
    notes: [
      'Use value/onChange for controlled content.',
      'TinyMCE and its support assets must be served from the configured script path.',
    ],
  },
  {
    slug: 'form',
    name: 'Form',
    group: 'Form composition',
    summary: 'Composes typed input definitions, layout wrappers, and action buttons.',
    description:
      'A form composition helper that renders a list of Input definitions and optional actions inside a configurable element.',
    importName: 'Form',
    demo: 'form',
    code: `<Form inputs={[\n  { type: 'text', label: 'Name', properties: { value, onChange } },\n  { type: 'check', label: 'Accept terms', properties: { checked, onChange } },\n]} actions={[{ children: 'Save', type: 'submit' }]} />`,
    props: [
      {
        name: 'inputs',
        type: 'InputProps[]',
        defaultValue: '[]',
        description: 'Input definitions rendered by the dispatcher.',
      },
      {
        name: 'as',
        type: 'ElementType',
        defaultValue: "'form'",
        description: 'Element used as the outer form container.',
      },
      {
        name: 'actions',
        type: 'ButtonProps[]',
        defaultValue: '[]',
        description: 'Buttons rendered after the input collection.',
      },
      {
        name: 'inputsWrapper',
        type: 'InputsWrapperProps',
        defaultValue: '—',
        description: 'Grid wrapper configuration for inputs.',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Propagated to action button loading states.',
      },
      { name: 'condition', type: 'boolean', defaultValue: 'true', description: 'Returns null when false.' },
    ],
    notes: [
      'Input field values are controlled through each definition’s properties.',
      'Use action button type="submit" when handling a native submit event.',
    ],
  },
  {
    slug: 'input',
    name: 'Input',
    group: 'Form composition',
    summary: 'Dispatches a single input definition to its matching field component.',
    description:
      'A discriminated input dispatcher for text, search, textarea, select, checks, OTP, phone, password, upload, and more.',
    importName: 'Input',
    demo: 'input',
    code: `<Input type="text" label="Name" properties={{\n  value, onChange: (event) => setValue(event.target.value),\n}} />`,
    props: [
      { name: 'type', type: 'InputType', defaultValue: "'text'", description: 'Chooses the concrete input component.' },
      { name: 'label', type: 'ReactNode', defaultValue: '—', description: 'Label forwarded to the chosen field.' },
      {
        name: 'properties',
        type: 'type-specific props',
        defaultValue: '—',
        description: 'Native or component-specific field properties.',
      },
      { name: 'condition', type: 'boolean', defaultValue: 'true', description: 'Omits the field when false.' },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Loading state forwarded to supported fields.',
      },
    ],
    notes: [
      'Use the component-specific type so TypeScript can infer the matching props.',
      'Controlled inputs should receive both value and change handlers.',
    ],
  },
  {
    slug: 'inputs',
    name: 'Inputs',
    group: 'Form composition',
    summary: 'Renders an array of Input definitions inside a configurable grid wrapper.',
    description:
      'A lightweight field collection useful when you want the input dispatcher without the outer Form element or actions.',
    importName: 'Inputs',
    demo: 'inputs',
    code: `<Inputs inputs={[\n  { type: 'text', label: 'First name', properties: { value, onChange } },\n  { type: 'textarea', label: 'Bio', properties: { value: bio, onChange: setBio } },\n]} />`,
    props: [
      { name: 'inputs', type: 'InputProps[]', defaultValue: '[]', description: 'Fields rendered in order.' },
      {
        name: 'wrapper.size',
        type: 'WrapperSize[]',
        defaultValue: "['grid-cols-12']",
        description: 'Grid column utility classes.',
      },
      {
        name: 'wrapper.className',
        type: 'string',
        defaultValue: "'items-start gap-3 w-full'",
        description: 'Classes applied to the grid wrapper.',
      },
      {
        name: 'empty',
        type: 'ReactNode',
        defaultValue: '—',
        description: 'Content returned when no input definition remains.',
      },
    ],
    notes: [
      'Each field is rendered by Input and supports its type-specific API.',
      'Use stable conditions to hide fields that are not currently relevant.',
    ],
  },
  {
    slug: 'conditional-wrapper',
    name: 'ConditionalWrapper',
    group: 'Helpers',
    summary: 'Wraps children conditionally and supports a fallback wrapper.',
    description:
      'A helper for optional element composition based on a child condition and fallback wrapper configuration.',
    importName: 'ConditionalWrapper',
    demo: 'conditional-wrapper',
    code: `<ConditionalWrapper\n  childrenCondition={Boolean(link)}\n  fallback={{ as: 'div', attributes: { className: 'rounded-xl p-4' } }}\n>\n  Content\n</ConditionalWrapper>`,
    props: [
      {
        name: 'childrenCondition',
        type: 'boolean',
        defaultValue: 'false',
        description: 'Controls whether the primary wrapper is used.',
      },
      {
        name: 'children',
        type: 'ReactNode',
        defaultValue: '—',
        description: 'Content passed through the selected wrapper.',
      },
      {
        name: 'wrapper',
        type: 'wrapper configuration',
        defaultValue: '—',
        description: 'Primary element/component wrapper props.',
      },
      {
        name: 'fallback',
        type: 'wrapper configuration',
        defaultValue: '—',
        description: 'Optional wrapper configuration when condition is false.',
      },
    ],
    notes: [
      'Use it for small composition differences; avoid hiding complex logic inside wrapper configuration.',
      'Check the component’s WrapperProps type for exact supported wrapper fields.',
    ],
  },
  {
    slug: 'content',
    name: 'Content',
    group: 'Helpers',
    summary: 'Renders data with custom renderers, loading state, and empty fallback.',
    description: 'A generic data renderer with optional conditional renderers and configurable loading/empty content.',
    importName: 'Content',
    demo: 'content',
    code: `<Content\n  data={items}\n  render={(item) => <span key={item.id}>{item.name}</span>}\n  empty={<p>No items yet.</p>}\n/>`,
    props: [
      { name: 'data', type: 'T[]', defaultValue: 'required', description: 'Items to render.' },
      {
        name: 'render',
        type: '(item: T, index: number) => ReactNode',
        defaultValue: 'required',
        description: 'Primary item renderer.',
      },
      {
        name: 'renderConditions',
        type: 'conditional renderer[]',
        defaultValue: '[]',
        description: 'Optional render rules for matching items.',
      },
      {
        name: 'loading / loader',
        type: 'boolean / ReactNode',
        defaultValue: 'false / default',
        description: 'Loading state and placeholder content.',
      },
      { name: 'empty', type: 'ReactNode', defaultValue: '—', description: 'Content shown for an empty collection.' },
    ],
    notes: [
      'Use stable React keys inside the render callback.',
      'Prefer an explicit empty state when no data is a meaningful condition.',
    ],
  },
]

export function getComponentDoc(slug: string) {
  return componentCatalog.find((entry) => entry.slug === slug)
}
